version: 2
project_name: emod
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    main: ./cmd/emod
    ldflags:
      - -s -w -X github.com/hpcsc/emod/internal/version.releaseTag={{ .Tag }}
archives:
  - formats:
      - tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      emod-
      {{- tolower .Os }}-
      {{- if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  # a tag with a prerelease part, such as v0.2.1-42.gabc1234, gives a prerelease
  prerelease: auto
  github:
    owner: hpcsc
    name: emod
