export function createStore() {
  return {
    nodes: [],
    edges: [],
    modelName: '',
    layoutPositions: {},
    arrowData: [],
    nodeOffsets: {},
    hiddenContexts: {},
    viewport: { offsetX: 0, offsetY: 0, zoomScale: 1 },
    interaction: {
      drag: null,
      pan: null,
      touch: null,
      highlighted: {},
      selectedNodeId: null,
      inlineEdit: null,
      ctxMenu: null,
      suppressDetailClick: false,
    },
    dom: {
      svg: null,
      nameDisplay: null,
      sourceInput: null,
      renderBtn: null,
      statusEl: null,
      statNodes: null,
      statEdges: null,
      statCanvas: null,
      panel: null,
      panelHdr: null,
      panelBody: null,
      minimap: null,
      minimapSvg: null,
      minimapToggle: null,
      contextPanel: null,
      contextToggle: null,
      contextList: null,
      tooltip: null,
      detailPanel: null,
      dpContent: null,
      ctxMenu: null,
      actorAnnotations: null,
      resetLayoutBtn: null,
      fitViewBtn: null,
    },
  };
}
