name: CI

on:
  push: {}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'

    - name: Mise install
      uses: jdx/mise-action@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: task build

    - name: Run Unit Test
      run: task test:unit

    - name: Run Integration Test
      run: task test:integration

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: 'internal/viewer/package.json'

    - name: Run Viewer JS Tests
      run: task test:viewer

    - name: Run E2E Test
      run: task test:e2e

